Move and zoom camera to make points visible
fluttercommunity/arcgis_map_sdk pull request #56
Opened 2023-11-28 07:50 UTC by sbergmair

Camera automatically zooms and moves to make given list of points visible.

Issue: https://github.com/fluttercommunity/arcgis_map_sdk/issues/55

2023-11-28 12:14 UTC, JulianBissekkou requested changes

2023-11-28 12:14 UTC, JulianBissekkou commented on arcgis_map_sdk_android/android/src/main/kotlin/dev/fluttercommunity/arcgis_map_sdk_android/ArcgisMapView.kt
> +
nit: can you reformat this file?

2023-11-28 12:14 UTC, JulianBissekkou commented on arcgis_map_sdk_ios/ios/Classes/ArcgisMapView.swift
> +        let polyline = AGSPolyline(points: payload.points.map { latLng in AGSPoint(x: latLng.longitude,y:latLng.latitude,spatialReference:.wgs84())
I quickly formatted this for you
```suggestion
        let polyline = AGSPolyline(points: payload.points.map { latLng in AGSPoint(x: latLng.longitude, y:latLng.latitude, spatialReference: .wgs84())
```

2023-11-28 12:14 UTC, JulianBissekkou commented on arcgis_map_sdk_ios/ios/Classes/ArcgisMapView.swift
> +}
```suggestion
struct MoveToPointsPayload : Codable {
    let points: [LatLng]
    let padding: Double?
}
```

2023-11-28 12:14 UTC, JulianBissekkou commented on arcgis_map_sdk_method_channel/lib/src/method_channel_arcgis_map_plugin.dart
> +
No need to force unwrap this value
```suggestion
  @override
  Future<void> moveCameraToPoints({
    required List<LatLng> points,
    required int mapId,
    double? padding,
  }) {
    return _methodChannelBuilder(mapId).invokeMethod<bool>(
      "move_camera_to_points",
      {
        "points": points.map((p) => p.toMap()).toList(),
        "padding": padding,
      },
    );
  }

```

2023-11-28 12:14 UTC, JulianBissekkou commented on example/lib/main.dart
> +  "APIKEY",
Any reason you changed this env variable name?

2023-11-28 12:14 UTC, JulianBissekkou commented on example/lib/main.dart
> +                  child: const Text('Make polyline visible'),
```suggestion
                  child: const Text('Zoom to polyline'),
```

2023-12-11 00:01 UTC, MatthaiosSait approved these changes
Solid 👍

2023-12-11 06:57 UTC, merged

2024-02-05 09:55 UTC, passsy commented
Manually merged it into `main`